version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-orderflow
    environment:
      POSTGRES_DB: clientes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  customer-service:
    build:
      context: ./customer-service
    container_name: customer-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  stock-service:
    build:
      context: ./stock-service
    container_name: stock-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres

  order-receiver-service:
    build:
      context: ./order-receiver-service
    container_name: order-receiver-service
    ports:
      - "8085:8085"
    depends_on:
      - customer-service
      - product-service
      - stock-service
      - order-service

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "8086:8086"

volumes:
  pgdata:
