version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-orderflow
    environment:
      POSTGRES_DB: clientes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  customer-service:
    build:
      context: ./customer-service
    container_name: customer-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres

volumes:
  pgdata:
